Repository dnd-al-krk/portal_frontend, pull requests merged in 2018-12, with the labels that each got.

#79 Feature/registration fixes updates checkboxes
  front/src/App.js
  front/src/common/InfoSnackbar.js
  front/src/common/Register.js
  front/src/common/SidebarNavigationList.js
  front/src/common/Terms.js
  front/src/common/TopAppBar.js
  front/src/pages/Home.js
  profiles/views.py
Labels: backend, bugfix, enhancement, frontend

#84 Feature/game sessions reporting
  front/src/common/ReportDialog.js
  front/src/pages/GameDetail.js
  front/src/pages/Games.js
  front/src/pages/GamesList.js
  front/src/pages/Home.js
  front/src/stores/GamesStore.js
  games/admin.py
  games/api/filters.py
  games/api/serializers.py
  games/api/views.py
  games/migrations/0008_auto_20181202_1524.py
  games/migrations/0009_gamesessionplayersignup_reported.py
  games/migrations/0010_gamesession_report_time.py
  games/models.py
Labels: backend, enhancement, frontend

#85 added reporting of extra players in the game session
  front/src/common/ReportDialog.js
  games/__tests__/test_models.py
  games/api/views.py
  games/models.py
Labels: backend, enhancement, frontend

#86 Feature/generate report on the game sessions
  front/src/common/ReportDialog.js
  games/admin.py
  games/models.py
  games/utils.py
  profiles/models.py
  templates/emails/games_report.html
Labels: backend, bugfix, enhancement

#100 Add cookie consent bar
  front/package-lock.json
  front/package.json
  front/src/App.js
Labels: enhancement, frontend

#99 JWT token auth rewritten and added refresh
  front/src/api.js
  front/src/common/Login.js
  front/src/common/Register.js
  front/src/constants.js
  front/src/pages/Games.js
  front/src/pages/PasswordReset.js
  front/src/pages/Profiles.js
  front/src/store.js
  front/src/stores/AdventuresStore.js
  front/src/stores/GamesStore.js
  front/src/stores/NavigationStore.js
  front/src/stores/TokenAuthorizationStore.js
  front/src/stores/UserStore.js
  profiles/api/serializers.py
  profiles/api/views.py
  settings/base.py
Labels: backend, enhancement, frontend

#101 added AL type for adventures
  games/constants.py
  games/migrations/0011_auto_20181223_1613.py
  games/models.py
Labels: backend, bugfix
